_target_: src.datamodules.musdb_datamodule.MusdbDataModule

data_dir: ${data_dir} # data_dir is specified in config.yaml

sample_rate: 44100

stem:
  - bass
  - drums
  - other
  - vocals


batch_size: 1
train_val_test_split: [55_000, 5_000, 10_000]
num_workers: 0
pin_memory: False
